name: Update Dulo XML on Google Drive

on:
  push:
    paths:
      - 'dulo.xml'

jobs:
  upload_to_drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload and Overwrite File
        uses: Jodebu/upload-to-drive@master
        with:
          target: 'dulo.xml'
          folder: '19de7qd0hoooanQgcd1BYYxFk3V20e-yD'
          credentials: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
